### ISSUE TITLE
Bias in word sampling introduced by use of modulo.

### ISSUE THREAD

**Issue by thomcc** [functional-tim/easypassword#1]
Using `%` to compute the index of the word, as you do [here](https://github.com/functional-tim/easypassword/blob/main/src/password.rs#L61) introduces bias.

Consider if your RNG generated values between 0 and 10, and you did `% 4`, you'd have:
```
0 -> 0
1 -> 1
2 -> 2
3 -> 3
4 -> 0
5 -> 1
6 -> 2
7 -> 3
8 -> 0
9 -> 1
10 -> 2
```

You'll note that that has two 3s, but 3 of everything else.

Using modulo/remainder directly, without rejection sampling, will introduce bias towards lower values. This is especially bad in a security critical context like a password generator.

I expect that `rand` has a method to sample without bias, though, so you don't have to worry about performing rejection sampling yourself.

**Comment by BlackHoleFox** [comment]
You should use [gen_range](https://docs.rs/rand/0.5.6/rand/trait.Rng.html#method.gen_range) instead, with the length of your wordlist.

**Comment by functional-tim** [comment]
I'll look into it. Thanks for the feedback to both of you.

**Comment by functional-tim** [comment]
I added gen_range(). I think the issues is closed with that.

**Comment by thomcc** [comment]
~~Sorry, you put gen_range in the wrong place. This is still biased (and thus not very secure).~~ Actually, it's fine. You now have an unnecessary use of modulo, though, which makes it look wrong.

**Comment by functional-tim** [comment]
Ah...I thought I removed the modulo...
I will remove it.
